USE LIGHTADVENTUREWORKSDW;
GO
CREATE TABLE dbo.Customers
(
CustomerKey INT NOT NULL,
FullName NVARCHAR(150) NULL,
EmailAddress NVARCHAR(50) NULL,
City NVARCHAR(30) NULL,
StateProvince NVARCHAR(50) NULL,
CountryRegion NVARCHAR(50) NULL,
CONSTRAINT PK_Customers PRIMARY KEY (CustomerKey)
);
GO